"""
schemas.py
────────────────────────────────────────────────────────────────────────────
Pydantic data models for the Student 1 Interview Preparation Guide module.
Defines schemas for agent extractions, guidelines, and final API responses.
"""

import uuid
from typing import List, Optional
from pydantic import BaseModel, Field


class GenerateGuideRequest(BaseModel):
    """Request model sent by .NET backend to generate an interview guide."""

    job_title: Optional[str] = Field(
        default="Software Engineer",
        description="Role or target position title",
    )
    target_role: Optional[str] = Field(
        default=None,
        description="Specific target role name",
    )
    job_description: str = Field(
        ...,
        description="Full job description text to analyze",
    )
    experience_level: Optional[str] = Field(
        default="Mid-Senior",
        description="Candidate seniority level",
    )
    company_name: Optional[str] = Field(
        default="Enterprise Partner",
        description="Hiring company name",
    )


class JobDescriptionExtraction(BaseModel):
    """Schema enforced on Agent 1 (The JD Analyzer) extraction output."""

    languages: List[str] = Field(
        default_factory=list,
        description="Extracted programming languages",
    )
    frameworks: List[str] = Field(
        default_factory=list,
        description="Extracted frameworks, libraries, and runtimes",
    )
    cloud_tools: List[str] = Field(
        default_factory=list,
        description="Cloud infrastructure, databases, CI/CD, and DevOps tools",
    )
    domain_concepts: List[str] = Field(
        default_factory=list,
        description="Core technical patterns and domain concepts",
    )
    role_technical_summary: str = Field(
        default="Standard engineering requirements",
        description="Concise synthesis of technical expectations",
    )


# Alias for backwards compatibility
ExtractedJdData = JobDescriptionExtraction


class StudyFocusArea(BaseModel):
    """
    Individual study guideline focus area for Theoretical or Practical section.
    Strictly focuses on concepts, architectural patterns, and production guidelines.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for focus area",
    )
    title: str = Field(
        ...,
        description="Actionable title of what to study or review",
    )
    section: str = Field(
        ...,
        description="Either 'Key Theoretical Areas' or 'Practical Implementation Focus'",
    )
    priority: str = Field(
        default="High Priority",
        description="Priority: 'Core Requirement', 'High Priority', or 'Practical Focus'",
    )
    estimated_study_time: str = Field(
        default="35-45 mins",
        description="Estimated study duration",
    )
    overview: str = Field(
        ...,
        description="Detailed explanation of why this pillar is critical for the job",
    )
    concepts_to_review: List[str] = Field(
        default_factory=list,
        description="List of 3 to 5 core concepts, principles, or mechanisms to review",
    )
    practical_application: str = Field(
        ...,
        description="Real-world production scenario or trade-off to practice explaining",
    )
    coach_tip: str = Field(
        ...,
        description="Actionable career coach tip on demonstrating senior mastery",
    )


class TheoreticalConcepts(BaseModel):
    """Theoretical concepts container generated by Agent 2."""

    theoretical_main_concepts: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Core theoretical principles and computer science foundations",
    )


class PracticalGuidelines(BaseModel):
    """Practical implementation guidelines container generated by Agent 2."""

    practical_implementation_guidelines: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Real-world hands-on production guidelines and patterns",
    )


class GuideGenerationResult(BaseModel):
    """Schema enforced on Agent 2 (The Guide Architect) structured output."""

    role_overview_summary: str = Field(
        ...,
        description="Technical career coach summary of role expectations",
    )
    theoretical_main_concepts: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Theoretical Main Concepts to master for this position",
    )
    practical_implementation_guidelines: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Practical Implementation Guidelines for production tasks",
    )
    pro_tips: List[str] = Field(
        default_factory=list,
        description="Strategic guidelines and communication frameworks",
    )
    preparation_checklist: List[str] = Field(
        default_factory=list,
        description="Actionable day-of-interview readiness checklist items",
    )


class InterviewGuideResponse(BaseModel):
    """
    Final validated response returned to the .NET backend and React frontend.
    """

    role_overview_summary: str = Field(
        ...,
        description="Technical career coach summary of the role expectations",
    )
    key_theoretical_areas: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Theoretical Main Concepts to master for this position",
    )
    practical_implementation_focus: List[StudyFocusArea] = Field(
        default_factory=list,
        description="Practical Implementation Guidelines for production tasks",
    )
    pro_tips: List[str] = Field(
        default_factory=list,
        description="Strategic guidelines and communication frameworks",
    )
    preparation_checklist: List[str] = Field(
        default_factory=list,
        description="Actionable day-of-interview readiness checklist items",
    )
    validation_notes: Optional[List[str]] = Field(
        default=None,
        description="Notes produced by the Validator Agent QA checks",
    )
    is_valid: Optional[bool] = Field(
        default=True,
        description="Whether output passed all QA integrity validations",
    )


# Alias for backwards compatibility
InterviewPrepGuideResponse = InterviewGuideResponse
